spring:
  application:
    name: blueprint demo
  sleuth:
    sampler:
      percentage: 0.25 # Percentage of requests to sample with sleuth
server:
  port: 9000
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'
eureka:
  client:
    serviceUrl:
      defaultZone: http://wherever.eureka.is/eureka
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health